### ISSUE TITLE
Visual Studio Code如何编写运行C程序？-徐杨的博客

### ISSUE THREAD

**Issue by xuyang9978** [xuyang9978/myblog#16]
http://www.xuyang.run/article?aid=8

**Comment by anbangli** [comment]
建议试一下新版 Dev-C++ 5.13：https://banzhusoft.github.io/devcpp-cn/

**Comment by xuyang9978** [comment]
> @anbangli
> 建议试一下新版 Dev-C++ 5.13：https://banzhusoft.github.io/devcpp-cn/

好的，感谢推荐，我去试试^_^
